//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int BatchNo { get; set; }
        public Nullable<int> Custid { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public Nullable<int> Totaldone { get; set; }
        public Nullable<byte> printed { get; set; }
        public string BatchStatus { get; set; }
        public string Notes { get; set; }
    }
}
