//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNote
    {
        public int sysid { get; set; }
        public string custid { get; set; }
        public Nullable<System.DateTime> notedate { get; set; }
        public string author { get; set; }
        public string note { get; set; }
    }
}
