//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int sysid { get; set; }
        public string Empss { get; set; }
        public string EmpFirstName { get; set; }
        public string SSn { get; set; }
        public string Contact { get; set; }
        public string EmergencyNo { get; set; }
        public string Pager { get; set; }
        public string EmpLastName { get; set; }
        public string Initials { get; set; }
        public Nullable<System.DateTime> DateOfHire { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
    }
}
