//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public int Custid { get; set; }
        public string Company { get; set; }
        public string ShortName { get; set; }
        public string Contact { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Calculation { get; set; }
        public string PrintIncolor { get; set; }
        public Nullable<int> Ytdmeters { get; set; }
        public Nullable<int> CurrentYear { get; set; }
        public string Notes { get; set; }
        public string emailAddress { get; set; }
    }
}
