//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuoteHeader()
        {
            this.QuoteDetails = new HashSet<QuoteDetail>();
        }
    
        public int QuotId { get; set; }
        public Nullable<int> Custid { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<decimal> Totalcost { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteDetail> QuoteDetails { get; set; }
    }
}
