//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RootsHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RootsHeader()
        {
            this.RootsDetails = new HashSet<RootsDetail>();
        }
    
        public int sysid { get; set; }
        public string Company { get; set; }
        public string FMS { get; set; }
        public Nullable<decimal> CFH { get; set; }
        public string MFG { get; set; }
        public string CoNum { get; set; }
        public Nullable<decimal> BeginRead { get; set; }
        public Nullable<decimal> EndRead { get; set; }
        public string RPS { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootsDetail> RootsDetails { get; set; }
    }
}
