//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_batchMeterReport
    {
        public Nullable<int> Batchno { get; set; }
        public Nullable<int> Custid { get; set; }
        public Nullable<int> mfgnum { get; set; }
        public string conum { get; set; }
        public string Mfgsize { get; set; }
        public Nullable<decimal> Afpopen { get; set; }
        public Nullable<decimal> Afpcheck { get; set; }
        public Nullable<decimal> Afperro { get; set; }
        public Nullable<decimal> Alopen { get; set; }
        public Nullable<decimal> Alcheck { get; set; }
        public Nullable<decimal> Alerror { get; set; }
        public Nullable<System.DateTime> Pdate { get; set; }
        public string Pby { get; set; }
        public string Rft { get; set; }
        public string Irbt { get; set; }
        public string Remarks { get; set; }
        public string Company { get; set; }
        public string Irat { get; set; }
        public int sysid { get; set; }
    }
}
