//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_IndexMeters
    {
        public int BatchNo { get; set; }
        public int Custid { get; set; }
        public string Company { get; set; }
        public Nullable<int> Totaldone { get; set; }
        public string BatchStatus { get; set; }
    }
}
